# This is a basic workflow to help you get started with Actions

name: Yarn Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Dependencies
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: install
    - name: Run Linter
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: lint
  build:
    runs-on: ubuntu-latest
    needs:
     - lint
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Dependencies
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: install
    - name: Generate Static Site
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: generate
    - name: Upload Built Site
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: static-latest
        # Directory containing files to upload
        path: dist
